name: Mobile build
on:
  push:
    branches:    
      - feature/adding-vue-router

jobs:
  main:
    name: Mobile build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install Cordova
        working-directory: ./mobile
        run: npm install -g cordova
      
      - name: Add Android platform
        working-directory: ./mobile
        run: cordova platform add android@latest

      - name: npm install UI project
        working-directory: ./webui
        run: npm install

      - name: Build App HTML file from UI project
        working-directory: ./webui
        run: npm run build-mobile

      - name: npm install mobile project
        working-directory: ./mobile
        run: npm install

      - name: Build Android app
        working-directory: ./mobile
        run: npm run build-android

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: ./mobile/platforms/android/app/build/outputs/apk/debug/app-debug.apk